# src/model/deepseek41_numerics.cmake — #48 (docs/deepseek41/103): writes the V4.1 NUMERICS MANIFEST header.
#
# Run at BUILD time by the custom command in src/CMakeLists.txt (`cmake -P`), whenever a listed input, the input list,
# the flags file, this script or the compiler binary is newer than the stamp. The manifest is text, one input per line:
#   ds41-numerics-manifest 1
#   compiler <the first line of `<CXX> --version`>
#   flag <name>=<value>          one per line of FLAGS (written at configure time by src/CMakeLists.txt)
#   file <path> <sha256>         one per path in LIST, in list order, relative to ROOT
# The header defines kDs41NumericsManifest as that text; the runtime hashes it into the disk key (ds41_prefix_disk_key).
# It is rewritten only when its content changes, so an input whose mtime moved but whose bytes did not (a checkout, a
# `touch`) does not recompile the includer. The stamp is always touched.
#
# Inputs (-D): ROOT (the repository), LIST (the input list), FLAGS (the flags file), CXX (the compiler), OUT (the
# header), STAMP (the stamp file).
foreach(v ROOT LIST FLAGS CXX OUT STAMP)
  if(NOT DEFINED ${v})
    message(FATAL_ERROR "deepseek41_numerics.cmake: -D${v}=... is required")
  endif()
endforeach()

# A text file's lines as a CMake list. CMake's list syntax would split a line at a ';' and would not split inside
# '[' ... ']', so those three characters are blanked first: the paths never contain them, and in a comment or a flag
# value they only need to change the manifest consistently.
function(ds41n_lines path out)
  file(READ "${path}" t)
  string(REGEX REPLACE "[][;]" " " t "${t}")
  string(REPLACE "\n" ";" t "${t}")
  set(${out} "${t}" PARENT_SCOPE)
endfunction()

set(lines "ds41-numerics-manifest 1")

execute_process(COMMAND "${CXX}" --version OUTPUT_VARIABLE ver ERROR_VARIABLE ver_err RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "deepseek41_numerics.cmake: `${CXX} --version` failed (${rc}): ${ver_err}")
endif()
string(REGEX MATCH "^[^\n]*" ver "${ver}")
string(REGEX REPLACE "[][;]" " " ver "${ver}")
list(APPEND lines "compiler ${ver}")

ds41n_lines("${FLAGS}" flags)
foreach(f IN LISTS flags)
  string(STRIP "${f}" f)
  if(NOT f STREQUAL "")
    list(APPEND lines "flag ${f}")
  endif()
endforeach()

ds41n_lines("${LIST}" inputs)
set(n 0)
foreach(l IN LISTS inputs)
  string(REGEX REPLACE "#.*$" "" l "${l}")
  string(STRIP "${l}" l)
  if(l STREQUAL "")
    continue()
  endif()
  if(NOT EXISTS "${ROOT}/${l}")
    message(FATAL_ERROR "deepseek41_numerics.cmake: ${l} is listed in ${LIST} but does not exist")
  endif()
  file(SHA256 "${ROOT}/${l}" h)
  list(APPEND lines "file ${l} ${h}")
  math(EXPR n "${n} + 1")
endforeach()

# The header: one C string literal per manifest line (adjacent literals concatenate), '\' and '"' escaped.
set(content "// Generated by src/model/deepseek41_numerics.cmake from src/model/deepseek41_numerics_inputs.txt -- do not edit.\n")
string(APPEND content "// The V4.1 disk prompt cache's numerics manifest (#48, docs/deepseek41/103): ${n} files.\n")
string(APPEND content "#pragma once\n\ninline constexpr char kDs41NumericsManifest[] =\n")
foreach(l IN LISTS lines)
  string(REPLACE "\\" "\\\\" l "${l}")
  string(REPLACE "\"" "\\\"" l "${l}")
  string(APPEND content "    \"${l}\\n\"\n")
endforeach()
string(APPEND content "    \"\";\n")

set(old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL content)
  file(WRITE "${OUT}" "${content}")
  message(STATUS "DeepSeek-V4.1 numerics manifest: ${n} files hashed, header updated")
endif()
file(TOUCH "${STAMP}")
